# Generated by Django 5.0.4 on 2024-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivered_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(null=True),
        ),
    ]
