# Generated by Django 5.0.4 on 2024-05-03 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("completed_orders", models.IntegerField(default=0)),
                ("total_orders", models.IntegerField(default=0)),
                ("quality_rating_count", models.IntegerField(default=0)),
                ("acknowledgement_count", models.IntegerField(default=0)),
                ("on_time_delivery_count", models.IntegerField(default=0)),
                (
                    "vendor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendors.vendor"
                    ),
                ),
            ],
            options={
                "db_table": "vendor_metrics",
            },
        ),
    ]
