# Generated by Django 5.0.4 on 2024-05-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_vendormetrics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="vendor_id",
            new_name="vendor",
        ),
        migrations.RenameField(
            model_name="vendormetrics",
            old_name="vendor_id",
            new_name="vendor",
        ),
        migrations.RenameField(
            model_name="vendorperformance",
            old_name="vendor_id",
            new_name="vendor",
        ),
    ]
