# Generated by Django 5.0.4 on 2024-05-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_rename_vendor_id_purchaseorder_vendor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendormetrics",
            old_name="acknowledgement_count",
            new_name="total_acknowledgement_count",
        ),
        migrations.AddField(
            model_name="vendormetrics",
            name="total_acknowledgement_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
