# Generated by Django 5.0.4 on 2024-05-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "vendors",
            "0006_rename_acknowledgement_count_vendormetrics_total_acknowledgement_count_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="vendor",
            new_name="vendor_id",
        ),
        migrations.RenameField(
            model_name="vendormetrics",
            old_name="vendor",
            new_name="vendor_id",
        ),
        migrations.RenameField(
            model_name="vendorperformance",
            old_name="vendor",
            new_name="vendor_id",
        ),
    ]
